# Generated by Django 3.2.2 on 2021-05-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='site_image/')),
                ('backround_image', models.ImageField(upload_to='site_image/')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_Profession', models.CharField(max_length=200)),
                ('owner_moto_line', models.CharField(max_length=500)),
                ('symbol_image_small', models.ImageField(upload_to='site_image/')),
                ('symbol_image_big', models.ImageField(upload_to='site_image/')),
            ],
        ),
    ]
