# Generated by Django 3.2.2 on 2021-05-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_socil_meadi_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='active_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_page', models.BooleanField()),
                ('resume_page', models.BooleanField()),
                ('portfolio_page', models.BooleanField()),
                ('blog_page', models.BooleanField()),
                ('contact_page', models.BooleanField()),
            ],
        ),
    ]
