# Generated by Django 3.2.2 on 2021-05-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_active_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='user_image/')),
                ('about_content', models.CharField(max_length=2000)),
            ],
        ),
    ]
