# Generated by Django 3.2.2 on 2021-05-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='service_icon/')),
                ('service_name', models.CharField(max_length=1000)),
                ('service_detail', models.CharField(max_length=2000)),
            ],
        ),
    ]
