# Generated by Django 3.2.2 on 2021-05-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_workprocces'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='clients_logo/')),
                ('clients_name', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
