# Generated by Django 3.2.2 on 2021-05-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_workhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.CharField(max_length=100)),
                ('ending', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=500)),
                ('institute_name', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
