# Generated by Django 3.2.2 on 2021-05-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_name', models.CharField(max_length=500)),
                ('clients_designation', models.CharField(blank=True, max_length=500)),
                ('clients_image', models.ImageField(blank=True, upload_to='cilents_image/')),
                ('company_name', models.CharField(blank=True, max_length=500)),
                ('detials', models.CharField(max_length=100)),
            ],
        ),
    ]
