# Generated by Django 3.2.2 on 2021-05-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
