# Generated by Django 3.2.2 on 2021-05-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20210519_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='socil_meadi_links',
            new_name='SocialMedia',
        ),
    ]
