# Generated by Django 3.2.2 on 2021-05-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_rename_socil_meadi_links_socialmedia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='active_page',
            new_name='ActivePage',
        ),
    ]
