# Generated by Django 3.2.2 on 2021-05-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_rename_active_page_activepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='contact_icon/')),
                ('details', models.CharField(max_length=400)),
            ],
        ),
    ]
