# Generated by Django 3.2.2 on 2021-05-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_contatinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('menu_class', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='about_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='detials',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='content',
            field=models.TextField(),
        ),
    ]
