# Generated by Django 3.2.2 on 2021-05-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20210522_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=200)),
                ('email_port', models.IntegerField()),
                ('user_email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=10)),
                ('email_tls', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='link',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
