# Generated by Django 3.2.2 on 2021-05-29 06:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0022_auto_20210528_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_image', models.ImageField(upload_to='post_image/')),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('post_ctegory', models.CharField(max_length=255)),
                ('intro', models.TextField(default='Reade More...', max_length=255)),
                ('body', ckeditor.fields.RichTextField(null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
