# Generated by Django 3.2.2 on 2021-05-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_page', models.BooleanField(default=True)),
                ('resume_page', models.BooleanField(default=True)),
                ('portfolio_page', models.BooleanField(default=True)),
                ('blog_page', models.BooleanField(default=True)),
                ('contact_page', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ActivePage',
        ),
    ]
