# Generated by Django 3.2.2 on 2021-05-30 00:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0025_auto_20210530_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_category_name', models.CharField(max_length=20)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, choices=[('1', 'css'), ('2', 'jq')], max_length=32, null=True)),
                ('code', ckeditor.fields.RichTextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='PageActive',
            new_name='ActivePage',
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_image', models.ImageField(upload_to='post_image/')),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('intro', models.TextField(default='Reade More...', max_length=255)),
                ('body', ckeditor.fields.RichTextField(null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_ctegory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='frontend.blogcategory', verbose_name='post_ctegory')),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='frontend.blog'),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
