# Generated by Django 3.2.2 on 2021-05-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_auto_20210530_0639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
