# Generated by Django 3.2.2 on 2021-05-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_postcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='Comment',
        ),
    ]
