# Generated by Django 3.2.2 on 2021-06-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_auto_20210601_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, choices=[('1', 'css'), ('2', 'jq')], max_length=32, null=True)),
                ('code', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomCode',
        ),
    ]
