# Generated by Django 3.2.2 on 2021-06-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_auto_20210604_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
