# Generated by Django 3.2.2 on 2021-06-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_customscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
